### ISSUE TITLE
Request for inclusion of our NeurIPS-23 paper

### ISSUE THREAD

**Issue by GuanSuns** [hyp1231/awesome-llm-powered-agent#17]
Dear authors,

We hope this comment finds you well. We wanted to take a moment to bring your attention to a relevant paper from our lab that has recently been accepted to NeurIPS 2023:

[Leveraging Pre-trained Large Language Models to Construct and Utilize World Models for Model-based Task Planning](https://arxiv.org/abs/2305.14909) — The key idea of this work is to extract an explicit domain with LLM and thereby allow the agent to use external symbolic task planner.

We would be grateful if you would consider including our papers in your survey. We believe it would greatly benefit the readers interested in this burgeoning area of LLM-driven agents.

Best regards
Lin

**Comment by hyp1231** [comment]
Thanks for the contribution! Have included. 6bde4d6
