### ISSUE TITLE
More resource

### ISSUE THREAD

**Issue by billxbf** [hyp1231/awesome-llm-powered-agent#2]
Great collection! See how you like ReWOO since it's parallel to ReAct.
https://github.com/billxbf/ReWOO

**Comment by hyp1231** [comment]
Thanks for the nice suggestion! I would like to categorize it as "General Reasoning, Planning & Tool Using", do you think it's appropriate?

**Comment by billxbf** [comment]
Yes! that's what I think of as well

**Comment by hyp1231** [comment]
Thanks! Have updated the list. ❤️ [a48f4cb](https://github.com/hyp1231/awesome-llm-powered-agent/commit/a48f4cb9df37969f1f382f3b45669a4b57f8d8b0)
