### ISSUE TITLE
Reflexion Paper might not work

### ISSUE THREAD

**Issue by isamu-isozaki** [hyp1231/awesome-llm-powered-agent#31]
Hi! Thanks for the repo. There was a paper from Deepmind ["Large Language Models Cannot Self-Correct Reasoning Yet"](https://arxiv.org/abs/2310.01798) that seemed to say that Reflexion(which is listed in this repo) or any self-correction methods up to this point don't seem to work. The criticism for Reflexion in particular was that the authors used oracle labels(ground truth) for evaluation and I think they claimed removing that removed the performance gains. I think technically the part the paper agreed on is that external feedback can be useful.

**Comment by hyp1231** [comment]
Thanks for sharing such nice work! Yes, the debate is interesting and valuable. As a good complement, I've added this work to the list. 73e44bfab82a321b8d805071f8bafd55b58aadae
